# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mPpJeB3tIwIzt2W1IDJBTajVaLabnIps
"""

from typing import Union

Number = Union[int, float]

def _trim(s: str) -> str:
    s = s.rstrip("0").rstrip(".")
    return s if s else "0"

def _fmt_amount(x: Number) -> str:
    v = float(x)
    return f"{v:.1f}" if v.is_integer() else _trim(f"{v:.2f}")

def _fmt_rate(r: Number) -> str:
    v = float(r)
    return _trim(f"{v:.2f}") if v >= 1 else _trim(f"{v:.6f}")

def _fmt_inverse(r: Number) -> str:
    v = float(r)
    return _trim(f"{v:.2f}") if v >= 1 else _trim(f"{v:.4f}")

def format_result(date_str: str, base: str, target: str, rate: Number, from_amount: Number) -> str:
    r = float(rate)
    if r <= 0:
        raise ValueError("rate must be positive")
    amt_from = float(from_amount)
    amt_to = amt_from * r
    inv = 1.0 / r
    line1 = f"On {date_str}, the rate from {base} to {target} was {_fmt_rate(r)}."
    line2 = f"{_fmt_amount(amt_from)} {base} equals {_fmt_amount(amt_to)} {target}."
    line3 = f"Inverse rate: {_fmt_inverse(inv)}."
    return "\n".join([line1, line2, line3])